[workspace]
members = ["mdpos", "mdpos-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/terrakernel/mdpos"

[workspace.dependencies]
mdpos = { path = "mdpos", version = "0.1.0" }
unicode-width = "0.2"
